# This is a basic workflow to help you get started with Actions

name: Webhook

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  webhookFire:
    env:
      commitmsgs: ${{ github.event.commits.*.message }}
      author: ${{ github.event.head_commit.author.name }}
      COMMITS_CHANNEL_WEBHOOK: ${{ secrets.COMMITS_CHANNEL_WEBHOOK }}
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fire a webhook
        run: python3 scripts/commit_message_webhook.py
